# Use a base image
FROM python:3.12.0-slim-bookworm

# Set environment variables
ENV PYTHONBUFFERED 1
ENV PYTHONWRITEBYTECODE 1
ENV APP=/app

# Change the working directory
WORKDIR $APP

# Copy the requirements file and install dependencies
COPY requirements.txt $APP
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Copy the rest of the application files
COPY . $APP

# Expose the port the application will run on
EXPOSE 8000

# Ensure the entrypoint script is executable
RUN chmod +x /app/entrypoint.sh

# Set the entrypoint script
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]

# Command to run the application
CMD ["gunicorn", "--bind", ":8000", "--workers", "3", "djangoproj.wsgi"]
